version: '3'
services:
  api:
    image: 'obasoro/backend'
    ports:
      - "8000:8000"
    volumes:
      - ./api.:/api
    restart: always
  frontend:
    image: 'obasoro/frontend'
    ports:
      - "3000:3000"
    volumes:
      - type: bind

        source : ./nginx/default.conf

        target: /etc/nginx/conf.d/default.conf

    restart: always